### ISSUE TITLE
nuget发布的似乎不是用的Newtonsoft.json

### ISSUE THREAD

**Issue by duuzi** [lhdboy/Toosame.EventBus#1]
nuget发布的似乎不是用的Newtonsoft.json,导致后面event如果是不带参的构造函数反序列化会报错

**Comment by lhdboy** [comment]
不好意思哈，nuget上最新发布的1.1.5是remove_autofac分支的，1.1.5升级到了ASP.NET Core 3.0所以序列化JSON的已经换成自带的System.Text.Json了，并且把Autofac支持移除了并使用了自带的依赖注入服务，因为我自己项目在用，稳定了抽空我会合并到master分支。

序列化报错的解决方案：
1.使用ASP.NET Core 2.2的项目，降级到1.1.2；
2.使用ASP.NET Core 3.0+的项目推荐使用nuget上最新发布的版本（但是无法使用Autofac）。

**Comment by duuzi** [comment]
好的！已经解决了谢谢！
